output "external_id" {
  value       = databricks_storage_credential.external.aws_iam_role[0].external_id
  description = "External ID generated by Databricks for trust policy condition"
}

output "credential_name" {
  value = databricks_storage_credential.external.id
}